application: fantasm-hr
version: bqworker
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: webob
  version: "1.1.1"
- name: lxml
  version: "2.3"
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"

handlers:

- url: /_ah/queue/deferred.*
  script: google.appengine.ext.deferred.application
  login: admin

- url: /.*
  script: main.APP
  login: admin
